version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user_db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    # http://localhost:8083
      image: mongo-express
      container_name: mongo-express1
      depends_on:
        - mongo
      ports:
        - "8083:8081"
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ADMINUSERNAME : root
        ME_CONFIG_MONGODB_ADMINPASSWORD  : password
  #      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongdb:27017/

        #  mongo-express web username and password for login
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: password